# QUESTIONS

1. Define Pytorch and how does it different from other deep learning frameworks like tensorflow ?

2. What is the use of .dtype , .shape and .device in pytorch ?

3. What is the difference between @ and * operations between tensors ?

4. What is the use of torch.bmm() ?

5. What is the use of .reshape() ?

6. What is the use of torch.where() ?

7. What is the use of torch.argmax() and torch.topk() ?

8. What is the use of torch.gather() ?

9. What is AutoGrad ? How we can track the operations performed on any tensor ?

10. What is computation graph ? How to Check the computation graph ?

11. What is the use of .backward() ?

12. What is one problem of AutoGrad ? And How to resolve that problem ?

13. Difference Between .cpu(), .cuda() and .to(device) ?

14. Difference Between .item() and .tolist() ?

15. What Happens If You Don’t Use torch.no_grad() During Inference ?

16. Difference Between .backward() and torch.autograd.grad() ?

# THEORY

1. PyTorch is a dynamic, Pythonic deep learning framework developed by Facebook AI, known for flexibility and research usability.

    
    TensorFlow is also a deep learning framework developed by Google, originally used static graphs for optimized deployment but now supports eager execution.

    
    PyTorch is preferred in research, while TensorFlow has strong production deployment tools.


2. .shape : This is a tuple that describes the dimensions of the tensor. torch.Size([2, 3]) tells us it's a 2D tensor with 2 rows and 3 columns.

    .device : This tells you where the tensor's data is physically stored. By default, it's on the cpu. If you have a compatible GPU, you can move it there (.to("cuda")) for massive speedups.

    .dtype : This describes the data type of the numbers inside the tensor. Notice it defaulted to torch.float32

3. "*" performs element-wise multiplication between tensors of the same shape (or broadcastable shape).
        
       Key Points:

       Shape must be same or broadcastable.

       it doesn't perform matrix multiplication.

       it is used in attention masking, gating, scaling.

    @ performs matrix multiplication (dot product for 1D, matrix multiply for 2D, batch matrix multiply for 3D). And it is equivalent to torch.matmul().

    Dimensional Behaviour -

    | Tensor Dimension | `*`          | `@`                         |
    | ---------------- | ------------ | --------------------------- |
    | 1D               | Element-wise | Dot product                 |
    | 2D               | Element-wise | Matrix multiplication       |
    | 3D               | Element-wise | Batch matrix multiplication |


4. torch.bmm() performs batch matrix multiplication but only works on 3D tensors and does not support broadcasting.

       example -
       a = torch.randn(5, 2, 3)
       b = torch.randn(5, 3, 4)
       output = torch.bmm(a, b)
       print(output.shape)   # (5, 2, 4)

5. torch.reshape() returns a tensor with the same data but a new shape, without changing the values.

    and its syntax is -
    
    torch.reshape(input, new_shape)

6. torch.where() is a PyTorch function used to select elements from tensors based on a condition, operating element-wise and fully compatible with autograd.

    syntax is torch.where(condition, value_if_true, value_if_false)

7. After a model makes a prediction, we often need to find the item with the highest score.

       torch.argmax(): Finds the index of the single maximum value.

       torch.topk(): Finds the k largest values and their indices.

8. In PyTorch, torch.gather() is used to select values from a tensor using index positions along a specific dimension.wise conditional selection between two tensors based on a boolean condition.

       its syntax is - torch.gather(input, dim, index)

       It gathers values from input along dimension dim using index.

       Example -
       import torch

       input = torch.tensor([[10, 20, 30],
                            [40, 50, 60]])

       index = torch.tensor([[0, 2],
                            [1, 0]])

       output = torch.gather(input, dim=1, index=index)
       print(output)

       and output will be:

       tensor([[10, 30],
        [50, 40]])

9. Autograd is PyTorch’s automatic differentiation engine that records the operations performed on tensors during the forward pass and builds a dynamic computation graph.

    To track the operations performed on any tensor we must use "requires_grad = True" as parameter while defining that tensor.

    By default, PyTorch assumes a tensor is just static data. To tell it that a tensor is a learnable parameter (like a model's weight or bias), you must set its requires_grad attribute to True.

10. Computation Graph is a directed acyclic graph that represents the sequence of operations performed on tensors during the forward pass. And it is used to compute gradients during backpropagation.

    to check the computation graph or the operations performed on a tensor we can use .grad_fn.

11. .backward() is used to compute gradients of a tensor with respect to all tensors that have "requires_grad = True" and stores them in the ".grad" attribute of leaf tensors.

12. One major issue with Autograd is that gradients accumulate by default. Each call to " .backward() " adds gradients to the existing " .grad values " instead of replacing them. To fix this, we must call " optimizer.zero_grad() " before the backward pass to clear old gradients.

        because accumulation of gradients will cause:
    
        > Wrong updates
    
        > Unstable training
    
        > Exploding gradients
    
        > Silent failures

    hence, to prevent this all we follow this in our training loop:

    optimizer.zero_grad() - clear old gradients

    loss.backward() - calculate gradients

    optimizer.step() - update weights

        and we use optimizer.zero_grad() before the loss.backward()
        because we want to clear gradients from the previous iteration before computing new ones.


13. .cpu() moves a tensor to CPU, .cuda() moves it to GPU, and .to(device) is a general method that moves tensors to a specified device. .to(device) is preferred because it makes code portable.

14. .item() -

    Converts a single-element tensor into Python scalar

    Works only for one-element tensors

        example -

        x = torch.tensor(5)
        x.item()  # 5

    .tolist() -

    Converts tensor to Python list

    Works for multi-element tensors

        example -

        x = torch.tensor([1, 2, 3])
        x.tolist()  # [1, 2, 3]

15. If torch.no_grad() is not used during inference, PyTorch will track gradients and build a computation graph, leading to unnecessary memory usage and slower execution.

        hence, correct inference pattern -
    
        model.eval()
    
        with torch.no_grad():
    
        outputs = model(inputs)

16. " .backward() " computes gradients and stores them in .grad, while  " torch.autograd.grad() " computes and returns gradients explicitly without modifyin .grad.

# CODING QUESTIONS


1. How to install and use pytorch on various platforms ?

2. How to check whether our installation recognizes our built-in NVIDIA GPU or not ?

3. What are the various methods to create tensors ?

4. How to check the datatype, shape and device of any tensor ?

5. Perform basic mathematical operations on tensor like:
    
       i) element-wise multiplication and matrix multiplication

       ii) calculate sum, mean, maximum, minimum values using "dim" parameter

       iii) change the shape of tensor without changing the values of tensor

       iv) transpose the tensor

6. Perform Indexing and Selcetion operations like:

       i) Standard Indexing: The Basics

       ii) Boolean Masking: Selection by Condition

       iii) Conditional Creation using torch.where()

       iv) Primitives for Finding the "Best" Items using torch.argmax() and torch.topk()

       v) Primitive for Dynamic Lookups using torch.gather()

7. AUTOGRAD

In [ ]:
# HOW TO INSTALL PYTORCH

!pip install torch
import torch
torch.__version__


'2.9.0+cpu'

In [ ]:
# How to check whether our installation recognizes our built-in NVIDIA GPU
# if it returns True , then it means it recognizes built-in NVIDIA GPU
# if it returns False , then no.

torch.cuda.is_available()

False

## Various methods to create tensors
1. Basic
2. From python lists
3. Creation from a Desired Shape
4. Creation by Mimicking Another Tensor's Properties


In [ ]:
# BASIC

# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(tensor0d)
print(tensor1d)
print(tensor2d)
print(tensor3d)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
# This is the most straightforward. You have a Python list of numbers, and you want to convert it into a PyTorch tensor using torch.tensor().

import torch

# Input: A standard Python list
data = [[1, 2, 3], [4, 5, 6]]
my_tensor = torch.tensor(data)

print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Creation from desired shape

# Input: A shape tuple (2 rows, 3 columns)
shape = (2, 3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(f"Ones Tensor:\n {ones}\n")
print(f"Zeros Tensor:\n {zeros}\n")
print(f"Random Tensor:\n {random}")

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random Tensor:
 tensor([[-1.0168,  0.5139,  0.3082],
        [ 0.6723,  1.3068, -0.6924]])


In [ ]:
# Often, you have an existing tensor and you need to create a new one that has the exact same shape, data type, and is on the same device.
# Instead of manually copying these properties, PyTorch provides handy _like functions.


template = torch.tensor([[1, 2], [3, 4]])

# Create new tensors with the same properties as the template
ones_like = torch.ones_like(template)
rand_like = torch.randn_like(template, dtype=torch.float) # dtype can be overridden

print(f"Template Tensor:\n {template}\n")
print(f"Ones_like Tensor:\n {ones_like}\n")
print(f"Randn_like Tensor:\n {rand_like}")


Template Tensor:
 tensor([[1, 2],
        [3, 4]])

Ones_like Tensor:
 tensor([[1, 1],
        [1, 1]])

Randn_like Tensor:
 tensor([[-1.0020,  0.6236],
        [ 0.0717, -0.4501]])


# Shape, Type, and Device of tensor


In [ ]:
# Every tensor has attributes that describe its metadata with .shape, .dtype, and .device.

# Let's create a tensor to inspect
tensor = torch.randn(2, 3)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Basic Mathematical & Reduction Operations


In [ ]:
# Mathematical Operations: * vs. @


a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20], [30, 40]])

# Calculation: [[1*10, 2*20], [3*30, 4*40]]
element_wise_product = a * b

print(f"Tensor a:\n {a}\n")
print(f"Tensor b:\n {b}\n")
print(f"Element-wise Product (a * b):\n {element_wise_product}")

m1 = torch.tensor([[1, 2, 3], [4, 5, 6]])   # Shape: (2, 3)
m2 = torch.tensor([[7, 8], [9, 10], [11, 12]]) # Shape: (3, 2)

# Calculation for the first element: (1*7) + (2*9) + (3*11) = 58
matrix_product = m1 @ m2 # Resulting shape: (2, 2)

print(f"Matrix 1 (shape {m1.shape}):\n {m1}\n")
print(f"Matrix 2 (shape {m2.shape}):\n {m2}\n")
print(f"Matrix Product (m1 @ m2):\n {matrix_product}")

Tensor a:
 tensor([[1, 2],
        [3, 4]])

Tensor b:
 tensor([[10, 20],
        [30, 40]])

Element-wise Product (a * b):
 tensor([[ 10,  40],
        [ 90, 160]])
Matrix 1 (shape torch.Size([2, 3])):
 tensor([[1, 2, 3],
        [4, 5, 6]])

Matrix 2 (shape torch.Size([3, 2])):
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

Matrix Product (m1 @ m2):
 tensor([[ 58,  64],
        [139, 154]])


In [ ]:
# Batch Multiplication
import torch

A = torch.randn(4, 3, 5)   # batch=4
B = torch.randn(4, 5, 2)

C = torch.bmm(A, B)
print(C.shape)  # torch.Size([4, 3, 2])


torch.Size([4, 3, 2])


In [ ]:
# Reduction Operations include sum(), mean(), max(), and min()

scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])

# By default, reductions apply to the entire tensor
total_sum = scores.sum()
average_score = scores.mean()

print(f"Scores Tensor:\n {scores}\n")
# Calculation: 10 + 20 + 30 + 5 + 10 + 15 = 90
print(f"Total Sum: {total_sum}")
# Calculation: 90 / 6 = 15
print(f"Overall Mean: {average_score}")

Scores Tensor:
 tensor([[10., 20., 30.],
        [ 5., 10., 15.]])

Total Sum: 90.0
Overall Mean: 15.0


In [ ]:
# dim Argument

scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])

# To get the sum FOR EACH ASSIGNMENT, we collapse the student dimension (dim=0)
# Calculation: [10+5, 20+10, 30+15]
sum_per_assignment = scores.sum(dim=0)

# To get the sum FOR EACH STUDENT, we collapse the assignment dimension (dim=1)
# Calculation: [10+20+30, 5+10+15]
sum_per_student = scores.sum(dim=1)

print(f"Original Scores:\n {scores}\n")
print(f"Sum per assignment (dim=0): {sum_per_assignment}")
print(f"Sum per student (dim=1):    {sum_per_student}")

Original Scores:
 tensor([[10., 20., 30.],
        [ 5., 10., 15.]])

Sum per assignment (dim=0): tensor([15., 30., 45.])
Sum per student (dim=1):    tensor([60., 30.])


In [ ]:
# tensor.reshape()

# Original shape: (2, 3)
# New shape: (3, 2)
# Total elements: 6 → must match

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y = x.reshape(3, 2)
print(y)

# PyTorch can infer one dimension automatically.
x1 = torch.randn(12)

y1 = x1.reshape(3, -1)
print(y1.shape)  # torch.Size([3, 4])



tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 4])


In [ ]:
# tensor.view()

x = torch.arange(6)
print(x)
# tensor([0, 1, 2, 3, 4, 5])

y = x.view(2, 3)
print(y)


In [ ]:
# tensor.T

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y = x.T
print(y)


tensor([[1, 4],
        [2, 5],
        [3, 6]])


# Indexing & Selection Primitives



In [ ]:
# Standard Indexing: The Basics

# A simple, easy-to-read tensor
x = torch.tensor([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11]])

# Get the second row (at index 1)
row_1 = x[1]
print(f"Row 1: {row_1}\n")

# Get the third column (at index 2)
col_2 = x[:, 2]
print(f"Column 2: {col_2}\n")

# Get a specific element (row 1, column 3)
element_1_3 = x[1, 3]
print(f"Element at (1, 3): {element_1_3}")

Row 1: tensor([4, 5, 6, 7])

Column 2: tensor([ 2,  6, 10])

Element at (1, 3): 7


In [ ]:
# Boolean Masking: Selection by Condition

x = torch.tensor([[0, 1, 2, 3], [4, 5, 6, 7]])

# Step 1: Create the boolean mask
mask = x > 3
print(f"The Boolean Mask (x > 3):\n {mask}\n")

# Step 2: Apply the mask to the tensor
selected_elements = x[mask]
print(f"Selected elements: {selected_elements}")

The Boolean Mask (x > 3):
 tensor([[False, False, False, False],
        [ True,  True,  True,  True]])

Selected elements: tensor([4, 5, 6, 7])


In [ ]:
# Conditional Creation: torch.where()

x = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a new tensor: if a value in x is > 4, use -1, otherwise use the original value
y = torch.where(x > 4, -1, x)

print(f"Original Tensor: {x}")
print(f"Result of where: {y}")

Original Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Result of where: tensor([ 0,  1,  2,  3,  4, -1, -1, -1, -1, -1])


In [ ]:
# Primitives for Finding the "Best" Items

scores = torch.tensor([
    [10, 0, 5, 20, 1],  # Scores for item 0
    [1, 30, 2, 5, 0]   # Scores for item 1
])

# Find the index of the best score for each item
best_indices = torch.argmax(scores, dim=1)
# For row 0, max is 20 at index 3. For row 1, max is 30 at index 1.
print(f"Argmax indices: {best_indices}\n")

# Find the top 3 scores and their indices for each item
top_values, top_indices = torch.topk(scores, k=3, dim=1)
print(f"Top 3 values:\n {top_values}\n")
print(f"Top 3 indices:\n {top_indices}")

Argmax indices: tensor([3, 1])

Top 3 values:
 tensor([[20, 10,  5],
        [30,  5,  2]])

Top 3 indices:
 tensor([[3, 0, 2],
        [1, 3, 2]])


In [ ]:
# Primitive for Dynamic Lookups: torch.gather()

data = torch.tensor([
    [10, 11, 12, 13],  # row 0
    [20, 21, 22, 23],  # row 1
    [30, 31, 32, 33]   # row 2
])

# Our "personalized list" of column indices to select from each row
indices_to_select = torch.tensor([[2], [0], [3]])

# Gather from `data` along dim=1 (the column dimension)
selected_values = torch.gather(data, dim=1, index=indices_to_select)

print(f"Selected Values:\n {selected_values}")

Selected Values:
 tensor([[12],
        [20],
        [33]])


# AUTOGRAD

In [ ]:
# A standard data tensor (we don't need to calculate gradients for our input data)
x_data = torch.tensor([[1., 2.], [3., 4.]])
print(f"Data tensor requires_grad: {x_data.requires_grad}\n")

# A parameter tensor (we need to learn this, so we need gradients)
w = torch.tensor([[1.0], [2.0]], requires_grad=True)
print(f"Parameter tensor requires_grad: {w.requires_grad}")

Data tensor requires_grad: False

Parameter tensor requires_grad: True


Once you set requires_grad=True, PyTorch starts building a computation graph behind the scenes. Think of it as a history of all the operations. Every time you perform an operation on a tensor that requires gradients, PyTorch adds a new node to this graph.

In [ ]:
# Three parameter tensors that we want to learn
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

# First operation: y = a + b
y = a + b

# Second operation: z = x * y
z = x * y

print(f"Result of a + b: {y}")
print(f"Result of x * y: {z}")

Result of a + b: 5.0
Result of x * y: 20.0


How can we prove this graph exists? Every tensor that is the result of an operation on a requires_grad tensor will have a special attribute called .grad_fn.

In [ ]:
# z was created by multiplication
print(f"grad_fn for z: {z.grad_fn}")

# y was created by addition
print(f"grad_fn for y: {y.grad_fn}")

# a was created by the user, not by an operation, so it has no grad_fn
print(f"grad_fn for a: {a.grad_fn}")

grad_fn for z: <MulBackward0 object at 0x7b372a076e60>
grad_fn for y: <AddBackward0 object at 0x7b37368cc250>
grad_fn for a: None


BASIC AUTOGRAD USING SCALAR

In [ ]:
x = torch.tensor(4.0, requires_grad=True)
y = torch.tensor(5.0, requires_grad=True)

# forward pass
z = x**2 + y**3
print(f"z = {x}^2 + {y}^3 = {z}")

# backward pass: compute gradients

z.backward()
dz_dx = x.grad # partial derivative wrt x
dz_dy = y.grad # partial derivative wrt y

print(f"dz/dx = {dz_dx} and dz/dy = {dz_dy}")

z = 4.0^2 + 5.0^3 = 141.0
dz/dx = 8.0 and dz/dy = 75.0


In [ ]:
# chain rule
x = torch.tensor(4.0, requires_grad=True)
y = x**2
z = y+1
w = z**2
print(f"x = {x} \ny = x^2 = {y} \nz = y+1 = {z} \nw = z^2 = {w}")

w.backward()

print(f"dw/dx = {x.grad}")

x = 4.0 
y = x^2 = 16.0 
z = y+1 = 17.0 
w = z^2 = 289.0
dw/dx = 272.0


One Problem Of Autograd Is the Accumulation Of Gradients.

see with example

In [ ]:
x = torch.tensor(2.0, requires_grad=True)

y = x * x
y.backward()

print(x.grad)  # 4

y = x * x
y.backward()

print(x.grad)

tensor(4.)
tensor(8.)
